version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition.py --output output/dataset/input.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset/input.csv.gz

  clean_dataset:
    run: r:v2 analysis/dataset_clean/dataset_clean.R
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        dataset: output/dataset_clean/input_clean.rds
      moderately_sensitive:
        flow: output/dataset_clean/flow.csv
        describe_inex: output/describe/inex_dataset.txt
        describe_preprocessed: output/describe/preprocessed_dataset.txt
        describe_qa: output/describe/qa_dataset.txt
        describe_ref: output/describe/ref_dataset.txt
  
  create_table_1:
   run: r:v2 analysis/tables/create_table1.R
   needs: [clean_dataset]
   outputs:
     moderately_sensitive:
       table_one: output/tables/table1.csv
       table_one_midpoint6: output/tables/table1_midpoint6.csv
