version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz
  
  create_table1:
    run: r:v2 analysis/table1/create_table1.R
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        table_one: output/tables/table1.csv


